### ISSUE TITLE
RuntimeError at Ray Serve Deployment: Mismatched Devices 

### ISSUE THREAD

**Issue by simonChoi034** [facebookresearch/SONAR#3]
When running the model under Ray Serve, I encountered a RuntimeError suggesting a device mismatch ("Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!"). 

**Error logs:**
```bash
(ServeReplica:default_FastAPIDeployment pid=3985235) ERROR 2023-08-25 08:10:39,337 default_FastAPIDeployment default_FastAPIDeployment#IxFVYy KOFVbAbqev /embedding default replica.py:636 - Request failed due to RayTaskError(DataPipelineError):
(ServeReplica:default_FastAPIDeployment pid=3985235) Traceback (most recent call last):
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/ray/serve/_private/replica.py", line 633, in invoke_single
(ServeReplica:default_FastAPIDeployment pid=3985235)     result = await method_to_call(*request_args, **request_kwargs)
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/ray/serve/_private/http_util.py", line 411, in __call__
(ServeReplica:default_FastAPIDeployment pid=3985235)     await self._asgi_app(
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
(ServeReplica:default_FastAPIDeployment pid=3985235)     await super().__call__(scope, receive, send)
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
(ServeReplica:default_FastAPIDeployment pid=3985235)     await self.middleware_stack(scope, receive, send)
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
(ServeReplica:default_FastAPIDeployment pid=3985235)     raise exc
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
(ServeReplica:default_FastAPIDeployment pid=3985235)     await self.app(scope, receive, _send)
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
(ServeReplica:default_FastAPIDeployment pid=3985235)     raise exc
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
(ServeReplica:default_FastAPIDeployment pid=3985235)     await self.app(scope, receive, sender)
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
(ServeReplica:default_FastAPIDeployment pid=3985235)     raise e
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
(ServeReplica:default_FastAPIDeployment pid=3985235)     await self.app(scope, receive, send)
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
(ServeReplica:default_FastAPIDeployment pid=3985235)     await route.handle(scope, receive, send)
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
(ServeReplica:default_FastAPIDeployment pid=3985235)     await self.app(scope, receive, send)
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
(ServeReplica:default_FastAPIDeployment pid=3985235)     response = await func(request)
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
(ServeReplica:default_FastAPIDeployment pid=3985235)     raw_response = await run_endpoint_function(
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
(ServeReplica:default_FastAPIDeployment pid=3985235)     return await dependant.call(**values)
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/Github/sonar_testing/source/deployments/fast_api.py", line 119, in encode_sentences
(ServeReplica:default_FastAPIDeployment pid=3985235)     embeddings = ray.get(ref)
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
(ServeReplica:default_FastAPIDeployment pid=3985235)     return fn(*args, **kwargs)
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
(ServeReplica:default_FastAPIDeployment pid=3985235)     return func(*args, **kwargs)
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/ray/_private/worker.py", line 2524, in get
(ServeReplica:default_FastAPIDeployment pid=3985235)     raise value.as_instanceof_cause()
(ServeReplica:default_FastAPIDeployment pid=3985235) ray.exceptions.RayTaskError(DataPipelineError): ray::ServeReplica:default_SentenceEncoder.handle_request() (pid=3985222, ip=192.168.4.101)
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
(ServeReplica:default_FastAPIDeployment pid=3985235)     return forward_call(*args, **kwargs)
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/sonar/models/sonar_text/model.py", line 112, in forward
(ServeReplica:default_FastAPIDeployment pid=3985235)     sentence_embeddings = self.sentence_embedding_pooling(
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/sonar/models/sonar_text/model.py", line 96, in sentence_embedding_pooling
(ServeReplica:default_FastAPIDeployment pid=3985235)     sentence_embedding = torch.einsum(
(ServeReplica:default_FastAPIDeployment pid=3985235)   File "/data/share/user/simon.choi/.virtualenv/sonar_testing/lib/python3.10/site-packages/torch/functional.py", line 378, in einsum
(ServeReplica:default_FastAPIDeployment pid=3985235)     return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
(ServeReplica:default_FastAPIDeployment pid=3985235) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Fix:**
It could be fixed by specifying the device when creating padding_mask under `source/models/sonar_text/model.py:80`

```
if padding_mask is None:
    padding_mask = torch.zeros(seqs.shape[:2], device=seqs.device)
```

**Comment by gulldan** [comment]
same problem, without ray serve,
same python 3.10

**Comment by simonChoi034** [comment]
> same problem, without ray serve, same python 3.10

I have created a pull request to fix this issue. The embedding model works fine when I run it with Ray Serve and normal python script. You can look into it.

**Comment by gulldan** [comment]
> I have created a pull request to fix this issue. The embedding model works fine when I run it with Ray Serve and normal python script. You can look into it.

my problem was i tried to predict only 1 sentence. You PR works!
thanks
