### ISSUE TITLE
Error while loading sonar.inference_pipelines.text.TextToEmbeddingModelPipeline

### ISSUE THREAD

**Issue by sl5035** [facebookresearch/SONAR#52]
Hello, I have installed fairseq2 using the install from source method - https://github.com/facebookresearch/fairseq2/blob/main/INSTALL_FROM_SOURCE.md

This is my pip list.
Package             Version
------------------- ----------
blobfile            3.0.0
certifi             2024.12.14
cffi                1.17.1
charset-normalizer  3.4.1
cmake               3.31.2
colorama            0.4.6
editdistance        0.8.1
fairseq2            0.3.0.dev0
fairseq2n           0.3.0.dev0
filelock            3.16.1
fsspec              2024.12.0
idna                3.10
importlib_metadata  7.2.1
importlib_resources 6.4.5
Jinja2              3.1.5
lxml                5.3.0
markdown-it-py      3.0.0
MarkupSafe          3.0.2
mdurl               0.1.2
mpmath              1.3.0
mypy-extensions     1.0.0
networkx            3.4.2
ninja               1.11.1.3
numpy               1.26.4
overrides           7.7.0
packaging           24.2
pip                 23.3.2
portalocker         3.0.0
psutil              5.9.8
pycparser           2.22
pycryptodomex       3.21.0
Pygments            2.18.0
PyYAML              6.0.2
regex               2024.11.6
requests            2.32.3
rich                13.9.4
sacrebleu           2.4.3
setuptools          67.8.0
sonar-space         0.3.2
soundfile           0.12.1
sox                 1.5.0
sympy               1.13.3
tabulate            0.9.0
tbb                 2021.8.0
tbb-devel           2021.8.0
tiktoken            0.8.0
torch               2.2.2
torcheval           0.0.7
tqdm                4.67.1
typing_extensions   4.12.2
urllib3             2.3.0
wheel               0.45.1
zipp                3.21.0

Below is the error I'm facing:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mac/Desktop/testenv/lib/python3.12/site-packages/sonar/inference_pipelines/__init__.py", line 7, in <module>
    from sonar.inference_pipelines.speech import (
  File "/Users/mac/Desktop/testenv/lib/python3.12/site-packages/sonar/inference_pipelines/speech.py", line 27, in <module>
    from sonar.models.sonar_text import load_sonar_text_decoder_model, load_sonar_tokenizer
  File "/Users/mac/Desktop/testenv/lib/python3.12/site-packages/sonar/models/sonar_text/__init__.py", line 37, in <module>
    from sonar.models.sonar_text.loader import (
  File "/Users/mac/Desktop/testenv/lib/python3.12/site-packages/sonar/models/sonar_text/loader.py", line 12, in <module>
    from fairseq2.models.nllb import load_nllb_tokenizer
ImportError: cannot import name 'load_nllb_tokenizer' from 'fairseq2.models.nllb' (/Users/mac/Desktop/testenv/lib/python3.12/site-packages/fairseq2/models/nllb/__init__.py)

I am currently using python==3.12.0 on an M2 Macbook Pro (Apple Silicon).

**Comment by nitishpandey04** [comment]
what is the error?

**Comment by sl5035** [comment]
oh perhaps my question is poorly formatted. below is the error im facing

Below is the error I'm facing:
Traceback (most recent call last):
File "", line 1, in
File "/Users/mac/Desktop/testenv/lib/python3.12/site-packages/sonar/inference_pipelines/init.py", line 7, in
from sonar.inference_pipelines.speech import (
File "/Users/mac/Desktop/testenv/lib/python3.12/site-packages/sonar/inference_pipelines/speech.py", line 27, in
from sonar.models.sonar_text import load_sonar_text_decoder_model, load_sonar_tokenizer
File "/Users/mac/Desktop/testenv/lib/python3.12/site-packages/sonar/models/sonar_text/init.py", line 37, in
from sonar.models.sonar_text.loader import (
File "/Users/mac/Desktop/testenv/lib/python3.12/site-packages/sonar/models/sonar_text/loader.py", line 12, in
from fairseq2.models.nllb import load_nllb_tokenizer
ImportError: cannot import name 'load_nllb_tokenizer' from 'fairseq2.models.nllb' (/Users/mac/Desktop/testenv/lib/python3.12/site-packages/fairseq2/models/nllb/init.py)

Would this be a version related error from fairseq2? Changing the line from

'from fairseq2.models.nllb import load_nllb_tokenizer' to 'from fairseq2.data.text.tokenizer.nllb import load_nllb_tokenizer' seems to be a temporary workaround for the solution.

**Comment by sl5035** [comment]
Update: installing fairseq2==0.2.1 and sonar-space==0.2.1 solved my problem
